//! Typed client for OpenRouter's dedicated image-generation API.
//!
//! This module owns provider mechanics only: the `/images` request wire,
//! authentication, observed response shapes, base64 decoding, remote-image
//! downloads, redirect policy, cancellation, timeout, and output-size bounds.
//! An embedding host still chooses the model and request defaults, resolves
//! reference-image paths, and decides where generated bytes are stored.

use std::collections::BTreeSet;
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};
use std::time::Duration;

use base64::Engine as _;
use base64::alphabet;
use base64::engine::general_purpose::STANDARD;
use base64::engine::{DecodePaddingMode, GeneralPurpose, GeneralPurposeConfig};
use futures::StreamExt;
use reqwest::redirect::Policy;
use reqwest::{StatusCode, Url};
use serde_json::{Value, json};
use tokio_util::sync::CancellationToken;

use crate::DEFAULT_BASE_URL;

const DEFAULT_TIMEOUT: Duration = Duration::from_secs(270);
const ERROR_BODY_CHARS: usize = 500;
const RESPONSE_METADATA_BYTES: u64 = 1024 * 1024;
const ERROR_BODY_CAPTURE_BYTES: u64 = 8 * 1024;
const MAX_DOWNLOAD_REDIRECTS: usize = 5;

/// Tolerant base64 decoding: missing padding is accepted, while malformed
/// payloads are rejected.
const FORGIVING_BASE64: GeneralPurpose = GeneralPurpose::new(
    &alphabet::STANDARD,
    GeneralPurposeConfig::new().with_decode_padding_mode(DecodePaddingMode::Indifferent),
);

/// One image supplied as an image-to-image reference.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageReference {
    pub media_type: String,
    pub bytes: Vec<u8>,
}

impl ImageReference {
    pub fn new(media_type: impl Into<String>, bytes: impl Into<Vec<u8>>) -> Self {
        Self {
            media_type: media_type.into(),
            bytes: bytes.into(),
        }
    }

    fn wire_value(&self) -> Value {
        json!({
            "type": "image_url",
            "image_url": {
                "url": format!(
                    "data:{};base64,{}",
                    self.media_type,
                    STANDARD.encode(&self.bytes)
                ),
            },
        })
    }
}

/// A request to OpenRouter's normalized image API.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageRequest {
    pub model: String,
    pub prompt: String,
    pub count: u32,
    pub output_format: String,
    pub aspect_ratio: Option<String>,
    pub quality: Option<String>,
    pub background: Option<String>,
    pub input_references: Vec<ImageReference>,
}

impl ImageRequest {
    pub fn new(model: impl Into<String>, prompt: impl Into<String>) -> Self {
        Self {
            model: model.into(),
            prompt: prompt.into(),
            count: 1,
            output_format: "png".to_string(),
            aspect_ratio: None,
            quality: None,
            background: None,
            input_references: Vec::new(),
        }
    }

    /// The exact JSON body sent to OpenRouter.
    pub fn body(&self) -> Value {
        let mut body = json!({
            "model": self.model,
            "prompt": self.prompt,
            "n": self.count,
            "output_format": self.output_format,
        });
        let object = body.as_object_mut().expect("object literal");
        if let Some(value) = self
            .aspect_ratio
            .as_deref()
            .filter(|value| !value.is_empty())
        {
            object.insert("aspect_ratio".to_string(), json!(value));
        }
        if let Some(value) = self.quality.as_deref().filter(|value| !value.is_empty()) {
            object.insert("quality".to_string(), json!(value));
        }
        if let Some(value) = self.background.as_deref().filter(|value| !value.is_empty()) {
            object.insert("background".to_string(), json!(value));
        }
        if !self.input_references.is_empty() {
            object.insert(
                "input_references".to_string(),
                Value::Array(
                    self.input_references
                        .iter()
                        .map(ImageReference::wire_value)
                        .collect(),
                ),
            );
        }
        body
    }
}

/// Decoded image bytes returned by OpenRouter.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedImage {
    pub bytes: Vec<u8>,
    pub media_type: Option<String>,
    pub revised_prompt: Option<String>,
    pub cost_usd: Option<f64>,
}

/// Network policy for provider-returned remote image URLs.
///
/// The production default accepts only public HTTPS targets. Tests or an
/// embedding host with an intentionally local fixture may allow exact origins
/// one at a time; an exception never carries across a redirect to another
/// origin.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RemoteImageDownloadPolicy {
    insecure_fixture_origins: BTreeSet<String>,
}

impl RemoteImageDownloadPolicy {
    pub fn public_https() -> Self {
        Self::default()
    }

    /// Allow one exact HTTP(S) origin to resolve to non-public addresses.
    ///
    /// This is intentionally explicit and origin-scoped for local test
    /// fixtures. Userinfo is never accepted, even for an allowed fixture.
    pub fn with_insecure_fixture_origin(
        mut self,
        origin: impl AsRef<str>,
    ) -> Result<Self, ImageDownloadPolicyError> {
        let raw = origin.as_ref();
        let url = Url::parse(raw).map_err(|error| ImageDownloadPolicyError {
            origin: raw.to_string(),
            reason: error.to_string(),
        })?;
        if !matches!(url.scheme(), "http" | "https") || url.host_str().is_none() {
            return Err(ImageDownloadPolicyError {
                origin: raw.to_string(),
                reason: "fixture origin must be an absolute HTTP(S) URL".to_string(),
            });
        }
        if has_url_credentials(&url) {
            return Err(ImageDownloadPolicyError {
                origin: origin_key(&url),
                reason: "fixture origin must not contain credentials".to_string(),
            });
        }
        self.insecure_fixture_origins.insert(origin_key(&url));
        Ok(self)
    }

    fn allows_insecure_fixture(&self, url: &Url) -> bool {
        self.insecure_fixture_origins.contains(&origin_key(url))
    }
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[error("invalid remote-image fixture origin {origin} ({reason})")]
pub struct ImageDownloadPolicyError {
    pub origin: String,
    pub reason: String,
}

#[derive(Debug, thiserror::Error, PartialEq)]
pub enum ImageError {
    #[error("aborted")]
    Aborted,
    #[error("timed out after {timeout_ms}ms waiting for the OpenRouter image API")]
    Timeout { timeout_ms: u128 },
    #[error("OpenRouter image API request failed — {message}")]
    Request { message: String },
    #[error("OpenRouter image API returned {status} {reason}{detail}")]
    HttpStatus {
        status: u16,
        reason: String,
        /// Empty, or already prefixed with ` — `.
        detail: String,
    },
    #[error("OpenRouter image API returned unreadable JSON — {message}")]
    InvalidJson { message: String },
    #[error("OpenRouter image API response is too large ({seen} bytes > {limit} limit)")]
    ApiResponseTooLarge { seen: u64, limit: u64 },
    #[error("OpenRouter image response contained no image (no b64_json / image_url / url)")]
    NoImage,
    #[error("OpenRouter image response carried undecodable base64 image data ({message})")]
    InvalidBase64 { message: String },
    #[error("content too large ({seen} bytes > {limit} limit)")]
    InlineTooLarge { seen: u64, limit: u64 },
    #[error("failed to fetch generated image from {url} ({message})")]
    RemoteRequest { url: String, message: String },
    #[error("refusing generated image URL {url} ({reason})")]
    RemoteUrlRejected { url: String, reason: String },
    #[error("failed to fetch generated image from {url} ({status})")]
    RemoteStatus { url: String, status: u16 },
    #[error("generated image from {url} is too large ({seen} bytes > {limit} limit)")]
    TooLarge { url: String, seen: u64, limit: u64 },
}

/// OpenRouter image-generation client.
///
/// API requests never follow redirects: they carry the bearer credential and
/// may contain private reference images. Remote image downloads use a separate
/// credential-free request, manual redirect validation, and DNS pinning.
pub struct OpenRouterImageClient {
    api_key: String,
    endpoint: String,
    timeout: Duration,
    api_http: reqwest::Client,
    download_policy: RemoteImageDownloadPolicy,
}

impl OpenRouterImageClient {
    pub fn new(api_key: impl Into<String>) -> Self {
        Self::with_endpoint(
            api_key,
            format!("{}/images", DEFAULT_BASE_URL.trim_end_matches('/')),
        )
    }

    pub fn with_base_url(api_key: impl Into<String>, base_url: impl AsRef<str>) -> Self {
        Self::with_endpoint(
            api_key,
            format!("{}/images", base_url.as_ref().trim_end_matches('/')),
        )
    }

    pub fn with_endpoint(api_key: impl Into<String>, endpoint: impl Into<String>) -> Self {
        let api_http = reqwest::Client::builder()
            .redirect(Policy::none())
            .build()
            .expect("OpenRouter image API client");
        Self {
            api_key: api_key.into(),
            endpoint: endpoint.into(),
            timeout: DEFAULT_TIMEOUT,
            api_http,
            download_policy: RemoteImageDownloadPolicy::default(),
        }
    }

    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    pub fn with_remote_download_policy(mut self, policy: RemoteImageDownloadPolicy) -> Self {
        self.download_policy = policy;
        self
    }

    pub fn endpoint(&self) -> &str {
        &self.endpoint
    }

    pub async fn generate(
        &self,
        request: &ImageRequest,
        cancel: &CancellationToken,
        max_output_bytes: u64,
    ) -> Result<GeneratedImage, ImageError> {
        tokio::select! {
            biased;
            _ = cancel.cancelled() => Err(ImageError::Aborted),
            _ = tokio::time::sleep(self.timeout) => Err(ImageError::Timeout {
                timeout_ms: self.timeout.as_millis(),
            }),
            output = self.generate_inner(request, max_output_bytes) => output,
        }
    }

    async fn generate_inner(
        &self,
        request: &ImageRequest,
        max_output_bytes: u64,
    ) -> Result<GeneratedImage, ImageError> {
        let response = self
            .api_http
            .post(&self.endpoint)
            .bearer_auth(&self.api_key)
            .header("Content-Type", "application/json")
            .json(&request.body())
            .send()
            .await
            .map_err(|error| ImageError::Request {
                message: error.to_string(),
            })?;
        let status = response.status();
        if !status.is_success() {
            let reason = status.canonical_reason().unwrap_or("").to_string();
            let body = read_error_body_prefix(response).await;
            let detail: String = body.chars().take(ERROR_BODY_CHARS).collect();
            return Err(ImageError::HttpStatus {
                status: status.as_u16(),
                reason,
                detail: if detail.is_empty() {
                    String::new()
                } else {
                    format!(" — {detail}")
                },
            });
        }
        let response_limit = encoded_response_limit(max_output_bytes);
        let body = read_success_body(response, response_limit).await?;
        let value: Value =
            serde_json::from_slice(&body).map_err(|error| ImageError::InvalidJson {
                message: error.to_string(),
            })?;
        let parsed = parse_response(&value)?;

        let (bytes, downloaded_media_type) = if let Some(base64) = parsed.base64 {
            let filtered: Vec<u8> = base64
                .bytes()
                .filter(|byte| !byte.is_ascii_whitespace())
                .collect();
            let bytes =
                FORGIVING_BASE64
                    .decode(filtered)
                    .map_err(|error| ImageError::InvalidBase64 {
                        message: error.to_string(),
                    })?;
            (bytes, None)
        } else if let Some(url) = parsed.remote_url {
            let (media_type, bytes) = self.download(&url, max_output_bytes).await?;
            (bytes, media_type)
        } else {
            return Err(ImageError::NoImage);
        };

        if bytes.len() as u64 > max_output_bytes {
            return Err(ImageError::InlineTooLarge {
                seen: bytes.len() as u64,
                limit: max_output_bytes,
            });
        }
        Ok(GeneratedImage {
            bytes,
            media_type: downloaded_media_type.or(parsed.media_type),
            revised_prompt: parsed.revised_prompt,
            cost_usd: parsed.cost_usd,
        })
    }

    async fn download(
        &self,
        url: &str,
        max_output_bytes: u64,
    ) -> Result<(Option<String>, Vec<u8>), ImageError> {
        let mut current = Url::parse(url).map_err(|error| ImageError::RemoteUrlRejected {
            url: "<invalid remote URL>".to_string(),
            reason: format!("invalid URL: {error}"),
        })?;

        for redirects in 0..=MAX_DOWNLOAD_REDIRECTS {
            let client = self.download_client_for(&current).await?;
            let current_url = current.to_string();
            let response = client.get(current.clone()).send().await.map_err(|error| {
                ImageError::RemoteRequest {
                    url: current_url.clone(),
                    message: error.to_string(),
                }
            })?;

            if follows_redirect(response.status()) {
                if redirects == MAX_DOWNLOAD_REDIRECTS {
                    return Err(ImageError::RemoteUrlRejected {
                        url: current_url,
                        reason: format!(
                            "too many redirects: exceeded {MAX_DOWNLOAD_REDIRECTS} redirects"
                        ),
                    });
                }
                let location = response
                    .headers()
                    .get(reqwest::header::LOCATION)
                    .ok_or_else(|| ImageError::RemoteUrlRejected {
                        url: current_url.clone(),
                        reason: format!(
                            "HTTP {} redirect has no Location header",
                            response.status()
                        ),
                    })?
                    .to_str()
                    .map_err(|error| ImageError::RemoteUrlRejected {
                        url: current_url.clone(),
                        reason: format!("invalid redirect Location header: {error}"),
                    })?;
                current =
                    current
                        .join(location)
                        .map_err(|error| ImageError::RemoteUrlRejected {
                            url: current_url,
                            reason: format!("invalid redirect target `{location}`: {error}"),
                        })?;
                // The next loop iteration validates and pins the redirect
                // target before any request can leave this process.
                continue;
            }

            if !response.status().is_success() {
                return Err(ImageError::RemoteStatus {
                    url: current_url,
                    status: response.status().as_u16(),
                });
            }
            let media_type = response
                .headers()
                .get(reqwest::header::CONTENT_TYPE)
                .and_then(|value| value.to_str().ok())
                .map(|value| value.split(';').next().unwrap_or(value).trim().to_string())
                .filter(|value| !value.is_empty());
            if let Some(length) = response.content_length()
                && length > max_output_bytes
            {
                return Err(ImageError::TooLarge {
                    url: current_url,
                    seen: length,
                    limit: max_output_bytes,
                });
            }

            let mut stream = response.bytes_stream();
            let mut body = Vec::new();
            while let Some(chunk) = stream.next().await {
                let chunk = chunk.map_err(|error| ImageError::RemoteRequest {
                    url: current_url.clone(),
                    message: error.to_string(),
                })?;
                let seen = (body.len() as u64).saturating_add(chunk.len() as u64);
                if seen > max_output_bytes {
                    return Err(ImageError::TooLarge {
                        url: current_url,
                        seen,
                        limit: max_output_bytes,
                    });
                }
                body.extend_from_slice(&chunk);
            }
            return Ok((media_type, body));
        }

        unreachable!("bounded redirect loop returns or advances")
    }

    async fn download_client_for(&self, url: &Url) -> Result<reqwest::Client, ImageError> {
        if has_url_credentials(url) {
            return Err(reject_remote_url(url, "credentials are not allowed"));
        }

        let fixture = self.download_policy.allows_insecure_fixture(url);
        if !matches!(url.scheme(), "http" | "https") {
            return Err(reject_remote_url(url, "only HTTPS URLs are allowed"));
        }
        if !fixture && url.scheme() != "https" {
            return Err(reject_remote_url(url, "HTTPS is required"));
        }

        let host = url
            .host_str()
            .ok_or_else(|| reject_remote_url(url, "URL has no host"))?;
        let port = url
            .port_or_known_default()
            .ok_or_else(|| reject_remote_url(url, "URL has no usable port"))?;

        let mut builder = reqwest::Client::builder()
            .redirect(Policy::none())
            // A proxy would resolve the hostname again and defeat the
            // validation/pinning performed here.
            .no_proxy();

        let ip_literal = host
            .strip_prefix('[')
            .and_then(|host| host.strip_suffix(']'))
            .unwrap_or(host)
            .parse::<IpAddr>();
        if let Ok(ip) = ip_literal {
            if !fixture && !is_public_ip(ip) {
                return Err(reject_remote_url(
                    url,
                    format!("IP address {ip} is not public"),
                ));
            }
        } else {
            let mut addresses: Vec<SocketAddr> = tokio::net::lookup_host((host, port))
                .await
                .map_err(|error| ImageError::RemoteRequest {
                    url: url.to_string(),
                    message: format!("DNS lookup failed: {error}"),
                })?
                .collect();
            addresses.sort_unstable();
            addresses.dedup();
            if addresses.is_empty() {
                return Err(ImageError::RemoteRequest {
                    url: url.to_string(),
                    message: "DNS lookup returned no addresses".to_string(),
                });
            }
            if !fixture
                && let Some(address) = addresses.iter().find(|address| !is_public_ip(address.ip()))
            {
                return Err(reject_remote_url(
                    url,
                    format!("DNS resolved to non-public IP {}", address.ip()),
                ));
            }
            // The request uses only this validated answer set. Reqwest keeps
            // the URL host for Host/SNI while dialing one of these addresses,
            // preventing a second resolver lookup from rebinding the request.
            builder = builder.resolve_to_addrs(host, &addresses);
        }

        builder.build().map_err(|error| ImageError::RemoteRequest {
            url: url.to_string(),
            message: error.to_string(),
        })
    }
}

fn follows_redirect(status: StatusCode) -> bool {
    matches!(
        status,
        StatusCode::MOVED_PERMANENTLY
            | StatusCode::FOUND
            | StatusCode::SEE_OTHER
            | StatusCode::TEMPORARY_REDIRECT
            | StatusCode::PERMANENT_REDIRECT
    )
}

fn has_url_credentials(url: &Url) -> bool {
    let authority_has_userinfo = url
        .as_str()
        .split_once("://")
        .and_then(|(_, rest)| rest.split(['/', '?', '#']).next())
        .is_some_and(|authority| authority.contains('@'));
    authority_has_userinfo || !url.username().is_empty() || url.password().is_some()
}

fn origin_key(url: &Url) -> String {
    url.origin().ascii_serialization()
}

fn reject_remote_url(url: &Url, reason: impl Into<String>) -> ImageError {
    ImageError::RemoteUrlRejected {
        url: safe_url(url),
        reason: reason.into(),
    }
}

fn safe_url(url: &Url) -> String {
    if !has_url_credentials(url) {
        return url.to_string();
    }
    let mut redacted = url.clone();
    let _ = redacted.set_username("redacted");
    let _ = redacted.set_password(None);
    redacted.to_string()
}

fn is_public_ip(ip: IpAddr) -> bool {
    match ip {
        IpAddr::V4(ip) => is_public_ipv4(ip),
        IpAddr::V6(ip) => is_public_ipv6(ip),
    }
}

fn is_public_ipv4(ip: Ipv4Addr) -> bool {
    let [a, b, c, d] = ip.octets();
    !matches!(
        (a, b, c, d),
        (0, ..)
            | (10, ..)
            | (100, 64..=127, ..)
            | (127, ..)
            | (169, 254, ..)
            | (172, 16..=31, ..)
            | (192, 0, 0, ..)
            | (192, 0, 2, ..)
            | (192, 88, 99, ..)
            | (192, 168, ..)
            | (198, 18..=19, ..)
            | (198, 51, 100, ..)
            | (203, 0, 113, ..)
            | (224..=255, ..)
    )
}

fn is_public_ipv6(ip: Ipv6Addr) -> bool {
    if let Some(v4) = ip.to_ipv4_mapped() {
        return is_public_ipv4(v4);
    }
    let segments = ip.segments();
    if ip.is_unspecified() || ip.is_loopback() || ip.is_multicast() {
        return false;
    }
    if
    // The currently allocated global-unicast space is 2000::/3. Reject
    // unallocated/reserved space instead of assuming it is Internet-safe.
    (segments[0] & 0xe000) != 0x2000
        // IETF protocol assignments are special-purpose unless a narrower
        // assignment says otherwise. Generated-image downloads do not need
        // those exceptions, so fail closed for the whole 2001::/23 block.
        || (segments[0] == 0x2001
            && ((segments[1] & 0xfe00) == 0 || segments[1] == 0x0db8))
        // Current IPv6 documentation space.
        || (segments[0] == 0x3fff && (segments[1] & 0xf000) == 0)
        // 6to4 is special-purpose and has no reason to appear as an image CDN
        // target. Reject it instead of trusting the embedded relay path.
        || segments[0] == 0x2002
    {
        return false;
    }
    true
}

/// A successful response is JSON containing either a small remote URL or an
/// inline base64 image. Base64 expands decoded bytes to `ceil(n / 3) * 4`;
/// the fixed allowance covers the JSON envelope, MIME, usage, and revised
/// prompt without leaving response aggregation unbounded.
fn encoded_response_limit(max_output_bytes: u64) -> u64 {
    let base64_bytes = (max_output_bytes.saturating_add(2) / 3).saturating_mul(4);
    base64_bytes.saturating_add(RESPONSE_METADATA_BYTES)
}

async fn read_success_body(response: reqwest::Response, limit: u64) -> Result<Vec<u8>, ImageError> {
    if let Some(length) = response.content_length()
        && length > limit
    {
        return Err(ImageError::ApiResponseTooLarge {
            seen: length,
            limit,
        });
    }

    let mut stream = response.bytes_stream();
    let mut body = Vec::new();
    while let Some(chunk) = stream.next().await {
        let chunk = chunk.map_err(|error| ImageError::InvalidJson {
            message: error.to_string(),
        })?;
        let seen = (body.len() as u64).saturating_add(chunk.len() as u64);
        if seen > limit {
            return Err(ImageError::ApiResponseTooLarge { seen, limit });
        }
        body.extend_from_slice(&chunk);
    }
    Ok(body)
}

/// Non-success responses expose at most the first 500 characters publicly.
/// Capture only a bounded byte prefix; a body read failure retains the prior
/// `text().await.unwrap_or_default()` behavior by returning no detail.
async fn read_error_body_prefix(response: reqwest::Response) -> String {
    let mut stream = response.bytes_stream();
    let mut body = Vec::new();
    while let Some(chunk) = stream.next().await {
        let Ok(chunk) = chunk else {
            return String::new();
        };
        let remaining = ERROR_BODY_CAPTURE_BYTES.saturating_sub(body.len() as u64) as usize;
        if remaining == 0 {
            break;
        }
        let take = remaining.min(chunk.len());
        body.extend_from_slice(&chunk[..take]);
        if body.len() as u64 >= ERROR_BODY_CAPTURE_BYTES || take < chunk.len() {
            break;
        }
    }
    String::from_utf8_lossy(&body).into_owned()
}

#[derive(Debug, Default, PartialEq)]
struct ParsedResponse {
    base64: Option<String>,
    remote_url: Option<String>,
    media_type: Option<String>,
    revised_prompt: Option<String>,
    cost_usd: Option<f64>,
}

fn parse_response(value: &Value) -> Result<ParsedResponse, ImageError> {
    let datum = value
        .get("data")
        .and_then(Value::as_array)
        .and_then(|data| data.first());
    let mut parsed = ParsedResponse {
        revised_prompt: datum
            .and_then(|item| item.get("revised_prompt"))
            .and_then(Value::as_str)
            .map(str::to_string),
        cost_usd: value
            .get("usage")
            .and_then(|usage| usage.get("cost"))
            .and_then(Value::as_f64),
        ..ParsedResponse::default()
    };

    if let Some(base64) = datum
        .and_then(|item| item.get("b64_json"))
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty())
    {
        parsed.base64 = Some(base64.to_string());
        return Ok(parsed);
    }

    let url = datum
        .and_then(|item| item.get("image_url"))
        .and_then(|image| image.get("url"))
        .and_then(Value::as_str)
        .or_else(|| {
            datum
                .and_then(|item| item.get("url"))
                .and_then(Value::as_str)
        });
    if let Some(url) = url {
        if let Some((media_type, base64)) = parse_data_url(url) {
            parsed.base64 = Some(base64);
            parsed.media_type = Some(media_type);
        } else {
            parsed.remote_url = Some(url.to_string());
        }
        return Ok(parsed);
    }
    Err(ImageError::NoImage)
}

fn parse_data_url(url: &str) -> Option<(String, String)> {
    let rest = url.strip_prefix("data:")?;
    let header_end = rest.find([';', ',']).unwrap_or(rest.len());
    let header = &rest[..header_end];
    let after = &rest[header_end..];
    let body = after
        .strip_prefix(',')
        .or_else(|| after.strip_prefix(";base64,"))?;
    if !url.to_ascii_lowercase().contains(";base64") {
        return None;
    }
    let media_type = if header.is_empty() {
        "image/png"
    } else {
        header
    };
    Some((media_type.to_string(), body.to_string()))
}

#[cfg(test)]
mod tests {
    use std::collections::VecDeque;
    use std::sync::{Arc, Mutex};

    use tokio::io::{AsyncReadExt, AsyncWriteExt};

    use super::*;

    struct Captured {
        head: String,
        body: String,
    }

    struct MockServer {
        base: String,
        captured: Arc<Mutex<Vec<Captured>>>,
    }

    async fn mock_server(responses: Vec<String>) -> MockServer {
        let listener = tokio::net::TcpListener::bind(("127.0.0.1", 0))
            .await
            .unwrap();
        let address = listener.local_addr().unwrap();
        let responses = Arc::new(Mutex::new(VecDeque::from(responses)));
        let captured = Arc::new(Mutex::new(Vec::new()));
        let sink = captured.clone();
        tokio::spawn(async move {
            loop {
                let Ok((mut socket, _)) = listener.accept().await else {
                    return;
                };
                let responses = responses.clone();
                let sink = sink.clone();
                tokio::spawn(async move {
                    let mut raw = Vec::new();
                    let (head, body) = loop {
                        let mut chunk = [0_u8; 4096];
                        let Ok(read) = socket.read(&mut chunk).await else {
                            return;
                        };
                        if read == 0 {
                            return;
                        }
                        raw.extend_from_slice(&chunk[..read]);
                        let Some(end) = raw.windows(4).position(|window| window == b"\r\n\r\n")
                        else {
                            continue;
                        };
                        let head = String::from_utf8_lossy(&raw[..end]).to_string();
                        let content_length = head
                            .lines()
                            .find_map(|line| {
                                let (name, value) = line.split_once(':')?;
                                name.trim()
                                    .eq_ignore_ascii_case("content-length")
                                    .then(|| value.trim().parse::<usize>().ok())
                                    .flatten()
                            })
                            .unwrap_or(0);
                        if raw.len() >= end + 4 + content_length {
                            let body =
                                String::from_utf8_lossy(&raw[end + 4..end + 4 + content_length])
                                    .to_string();
                            break (head, body);
                        }
                    };
                    sink.lock().unwrap().push(Captured { head, body });
                    let response = { responses.lock().unwrap().pop_front() };
                    if let Some(response) = response {
                        let _ = socket.write_all(response.as_bytes()).await;
                    }
                });
            }
        });
        MockServer {
            base: format!("http://{address}"),
            captured,
        }
    }

    fn response(status: u16, reason: &str, content_type: &str, body: &str) -> String {
        format!(
            "HTTP/1.1 {status} {reason}\r\nContent-Type: {content_type}\r\n\
             Content-Length: {}\r\nConnection: close\r\n\r\n{body}",
            body.len()
        )
    }

    fn chunked_response(status: u16, reason: &str, content_type: &str, body: &str) -> String {
        format!(
            "HTTP/1.1 {status} {reason}\r\nContent-Type: {content_type}\r\n\
             Transfer-Encoding: chunked\r\nConnection: close\r\n\r\n{:x}\r\n{body}\r\n0\r\n\r\n",
            body.len()
        )
    }

    #[test]
    fn typed_request_serializes_the_normalized_wire_shape() {
        let mut request = ImageRequest::new("provider/model", "make it blue");
        request.aspect_ratio = Some("16:9".to_string());
        request.quality = Some("high".to_string());
        request.background = Some("transparent".to_string());
        request.input_references = vec![ImageReference::new("image/png", b"ABC".to_vec())];
        assert_eq!(
            request.body(),
            json!({
                "model": "provider/model",
                "prompt": "make it blue",
                "n": 1,
                "output_format": "png",
                "aspect_ratio": "16:9",
                "quality": "high",
                "background": "transparent",
                "input_references": [{
                    "type": "image_url",
                    "image_url": { "url": "data:image/png;base64,QUJD" },
                }],
            })
        );
    }

    #[tokio::test]
    async fn inline_response_is_decoded_with_metadata() {
        let server = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            r#"{"data":[{"b64_json":"QUJD","revised_prompt":"better"}],"usage":{"cost":0.2}}"#,
        )])
        .await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", server.base));
        let output = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap();
        assert_eq!(output.bytes, b"ABC");
        assert_eq!(output.revised_prompt.as_deref(), Some("better"));
        assert_eq!(output.cost_usd, Some(0.2));
        let captured = server.captured.lock().unwrap();
        assert!(captured[0].head.starts_with("POST /images "));
        assert!(
            captured[0]
                .head
                .to_ascii_lowercase()
                .contains("authorization: bearer secret")
        );
        assert_eq!(
            serde_json::from_str::<Value>(&captured[0].body).unwrap()["model"],
            "provider/model"
        );
    }

    #[tokio::test]
    async fn inline_response_honors_the_decoded_size_bound() {
        let server = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            r#"{"data":[{"b64_json":"QUJD"}]}"#,
        )])
        .await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", server.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                2,
            )
            .await
            .unwrap_err();
        assert_eq!(error, ImageError::InlineTooLarge { seen: 3, limit: 2 });
    }

    #[tokio::test]
    async fn oversized_success_envelope_is_refused_before_aggregation() {
        let limit = encoded_response_limit(2);
        let declared = limit + 1;
        let server = mock_server(vec![format!(
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\n\
             Content-Length: {declared}\r\nConnection: close\r\n\r\n"
        )])
        .await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", server.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                2,
            )
            .await
            .unwrap_err();
        assert_eq!(
            error,
            ImageError::ApiResponseTooLarge {
                seen: declared,
                limit,
            }
        );
    }

    #[tokio::test]
    async fn chunked_success_envelope_is_refused_by_the_running_bound() {
        let limit = encoded_response_limit(0);
        let body = "x".repeat(limit as usize + 1);
        let server =
            mock_server(vec![chunked_response(200, "OK", "application/json", &body)]).await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", server.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                0,
            )
            .await
            .unwrap_err();
        assert_eq!(
            error,
            ImageError::ApiResponseTooLarge {
                seen: limit + 1,
                limit,
            }
        );
    }

    #[tokio::test]
    async fn oversized_error_body_is_captured_only_as_the_public_prefix() {
        let body = "x".repeat(ERROR_BODY_CAPTURE_BYTES as usize + 1024);
        let server = mock_server(vec![response(
            429,
            "Too Many Requests",
            "text/plain",
            &body,
        )])
        .await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", server.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                2,
            )
            .await
            .unwrap_err();
        assert_eq!(
            error,
            ImageError::HttpStatus {
                status: 429,
                reason: "Too Many Requests".to_string(),
                detail: format!(" — {}", "x".repeat(ERROR_BODY_CHARS)),
            }
        );
    }

    #[tokio::test]
    async fn remote_response_is_downloaded_with_type_and_size_bound() {
        let blob = mock_server(vec![response(200, "OK", "image/webp", "WEBP")]).await;
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            &json!({ "data": [{ "url": format!("{}/blob", blob.base) }] }).to_string(),
        )])
        .await;
        let policy = RemoteImageDownloadPolicy::public_https()
            .with_insecure_fixture_origin(&blob.base)
            .unwrap();
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base))
            .with_remote_download_policy(policy);
        let output = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                4,
            )
            .await
            .unwrap();
        assert_eq!(output.bytes, b"WEBP");
        assert_eq!(output.media_type.as_deref(), Some("image/webp"));
    }

    #[tokio::test]
    async fn chunked_remote_image_is_refused_by_the_running_bound() {
        let blob = mock_server(vec![chunked_response(200, "OK", "image/webp", "WEBP")]).await;
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            &json!({ "data": [{ "url": format!("{}/blob", blob.base) }] }).to_string(),
        )])
        .await;
        let policy = RemoteImageDownloadPolicy::public_https()
            .with_insecure_fixture_origin(&blob.base)
            .unwrap();
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base))
            .with_remote_download_policy(policy);
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                3,
            )
            .await
            .unwrap_err();
        assert_eq!(
            error,
            ImageError::TooLarge {
                url: format!("{}/blob", blob.base),
                seen: 4,
                limit: 3,
            }
        );
    }

    #[tokio::test]
    async fn default_policy_rejects_an_insecure_initial_target_without_dialing_it() {
        let blob = mock_server(vec![response(200, "OK", "image/png", "NO")]).await;
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            &json!({ "data": [{ "url": format!("{}/private.png", blob.base) }] }).to_string(),
        )])
        .await;
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap_err();
        assert!(matches!(
            error,
            ImageError::RemoteUrlRejected { ref reason, .. } if reason == "HTTPS is required"
        ));
        assert!(blob.captured.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn default_policy_rejects_a_private_https_initial_target() {
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            r#"{"data":[{"url":"https://127.0.0.1/private.png"}]}"#,
        )])
        .await;
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap_err();
        assert!(matches!(
            error,
            ImageError::RemoteUrlRejected { ref reason, .. }
                if reason.contains("is not public")
        ));
    }

    #[tokio::test]
    async fn default_policy_rejects_a_hostname_resolving_to_private_addresses() {
        let client = OpenRouterImageClient::with_endpoint("secret", "http://unused.invalid/images");
        let url = Url::parse("https://localhost/private.png").unwrap();
        let error = client.download_client_for(&url).await.unwrap_err();
        assert!(matches!(
            error,
            ImageError::RemoteUrlRejected { ref reason, .. }
                if reason.contains("DNS resolved to non-public IP")
        ));
    }

    #[tokio::test]
    async fn remote_target_credentials_are_rejected_before_network_io() {
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            r#"{"data":[{"url":"https://user:secret@example.com/private.png"}]}"#,
        )])
        .await;
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap_err();
        assert!(matches!(
            &error,
            ImageError::RemoteUrlRejected { reason, .. }
                if reason == "credentials are not allowed"
        ));
        assert!(!error.to_string().contains("secret"));
    }

    #[tokio::test]
    async fn every_redirect_target_is_revalidated_before_it_is_dialed() {
        let redirect_target = mock_server(vec![response(200, "OK", "image/png", "NO")]).await;
        let redirector = mock_server(vec![format!(
            "HTTP/1.1 302 Found\r\nLocation: {}/private.png\r\n\
             Content-Length: 0\r\nConnection: close\r\n\r\n",
            redirect_target.base
        )])
        .await;
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            &json!({ "data": [{ "url": format!("{}/start", redirector.base) }] }).to_string(),
        )])
        .await;
        let policy = RemoteImageDownloadPolicy::public_https()
            .with_insecure_fixture_origin(&redirector.base)
            .unwrap();
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base))
            .with_remote_download_policy(policy);
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap_err();
        assert!(matches!(
            error,
            ImageError::RemoteUrlRejected { ref reason, .. } if reason == "HTTPS is required"
        ));
        assert_eq!(redirector.captured.lock().unwrap().len(), 1);
        assert!(redirect_target.captured.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn an_allowed_fixture_redirect_keeps_existing_download_behavior() {
        let fixture = mock_server(vec![
            "HTTP/1.1 302 Found\r\nLocation: /image.webp\r\n\
             Content-Length: 0\r\nConnection: close\r\n\r\n"
                .to_string(),
            response(200, "OK", "image/webp", "WEBP"),
        ])
        .await;
        let api = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            &json!({ "data": [{ "url": format!("{}/start", fixture.base) }] }).to_string(),
        )])
        .await;
        let policy = RemoteImageDownloadPolicy::public_https()
            .with_insecure_fixture_origin(&fixture.base)
            .unwrap();
        let client = OpenRouterImageClient::with_endpoint("secret", format!("{}/images", api.base))
            .with_remote_download_policy(policy);
        let output = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                4,
            )
            .await
            .unwrap();
        assert_eq!(output.bytes, b"WEBP");
        assert_eq!(output.media_type.as_deref(), Some("image/webp"));
        assert_eq!(fixture.captured.lock().unwrap().len(), 2);
    }

    #[tokio::test]
    async fn api_redirect_is_not_followed_with_bearer_or_reference_bytes() {
        let collector = mock_server(vec![response(
            200,
            "OK",
            "application/json",
            r#"{"data":[{"b64_json":"QUJD"}]}"#,
        )])
        .await;
        let redirector = mock_server(vec![format!(
            "HTTP/1.1 307 Temporary Redirect\r\nLocation: {}/collect\r\n\
             Content-Length: 0\r\nConnection: close\r\n\r\n",
            collector.base
        )])
        .await;
        let client =
            OpenRouterImageClient::with_endpoint("secret", format!("{}/images", redirector.base));
        let mut request = ImageRequest::new("provider/model", "a cat");
        request.input_references = vec![ImageReference::new("image/png", b"PRIVATE".to_vec())];
        let error = client
            .generate(&request, &CancellationToken::new(), 1024)
            .await
            .unwrap_err();
        assert!(matches!(error, ImageError::HttpStatus { status: 307, .. }));
        assert!(collector.captured.lock().unwrap().is_empty());
    }

    #[tokio::test]
    async fn cancellation_wins_before_network_io() {
        let cancel = CancellationToken::new();
        cancel.cancel();
        let client = OpenRouterImageClient::with_endpoint("secret", "http://127.0.0.1:1/images");
        let error = client
            .generate(&ImageRequest::new("m", "p"), &cancel, 1024)
            .await
            .unwrap_err();
        assert_eq!(error, ImageError::Aborted);
    }

    #[tokio::test]
    async fn timeout_covers_the_entire_request_and_response() {
        let listener = tokio::net::TcpListener::bind(("127.0.0.1", 0))
            .await
            .unwrap();
        let endpoint = format!("http://{}/images", listener.local_addr().unwrap());
        tokio::spawn(async move {
            let Ok((socket, _)) = listener.accept().await else {
                return;
            };
            let _keep_open = socket;
            std::future::pending::<()>().await;
        });

        let client = OpenRouterImageClient::with_endpoint("secret", endpoint)
            .with_timeout(Duration::from_millis(10));
        let error = client
            .generate(
                &ImageRequest::new("provider/model", "a cat"),
                &CancellationToken::new(),
                1024,
            )
            .await
            .unwrap_err();
        assert_eq!(error, ImageError::Timeout { timeout_ms: 10 });
    }

    #[test]
    fn response_parser_accepts_all_observed_shapes() {
        let direct = parse_response(&json!({
            "data": [{ "b64_json": "QUJD", "revised_prompt": "better" }],
            "usage": { "cost": 0.1 },
        }))
        .unwrap();
        assert_eq!(direct.base64.as_deref(), Some("QUJD"));
        assert_eq!(direct.revised_prompt.as_deref(), Some("better"));
        assert_eq!(direct.cost_usd, Some(0.1));

        let nested = parse_response(
            &json!({ "data": [{ "image_url": { "url": "data:image/webp;base64,QUJD" } }] }),
        )
        .unwrap();
        assert_eq!(nested.base64.as_deref(), Some("QUJD"));
        assert_eq!(nested.media_type.as_deref(), Some("image/webp"));

        let remote =
            parse_response(&json!({ "data": [{ "url": "https://cdn.test/a.png" }] })).unwrap();
        assert_eq!(remote.remote_url.as_deref(), Some("https://cdn.test/a.png"));
        assert_eq!(
            parse_response(&json!({ "data": [{}] })),
            Err(ImageError::NoImage)
        );
    }

    #[test]
    fn remote_ip_policy_rejects_private_link_local_and_reserved_ranges() {
        for ip in [
            "127.0.0.1",
            "10.0.0.1",
            "169.254.169.254",
            "192.0.2.1",
            "224.0.0.1",
            "::1",
            "fc00::1",
            "fe80::1",
            "2001:db8::1",
            "2001:100::1",
            "2002:0808:0808::1",
            "3fff::1",
            "::ffff:127.0.0.1",
        ] {
            assert!(!is_public_ip(ip.parse().unwrap()), "{ip}");
        }
        for ip in ["1.1.1.1", "8.8.8.8", "2606:4700:4700::1111"] {
            assert!(is_public_ip(ip.parse().unwrap()), "{ip}");
        }
    }
}
